name: SuperSnyk 次
description: "Detects automated Snyk PRs and adds 'snyk' label. Combines PRs with the 'snyk' label into a single SuperSnyk 次 PR. If a SuperSnyk 次 PR already exists, it will be updated."
inputs:
  repo-token:
    description: "GitHub token i.e. secrets.GITHUB_TOKEN"
    required: true
    default: "CHANGE_ME"

runs:
  using: "composite"
  steps:
    - uses: TimonVS/pr-labeler-action@v3
      name: Detect and label Snyk PR for 次 SuperSnyk
      with:
        configuration-path: $GITHUB_ACTION_PATH/pr-labeler.yml
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
    - run: gh pr view --json labels | jq '.labels | .[] | select(.name == "snykk")'
      shell: bash
    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - uses: bobvanderlinden/combine-pull-requests@v3
      with:
        label: snyk
        repo-token: ${{ inputs.repo-token }}
    - run: chmod +x $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh
      shell: bash
    - name: Get Snyk PRs metadata
      run: $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
    - name: Create SuperSnyk 次 PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: 次 SuperSnyk
        body: "次 SuperSnyk PR created with [create-pull-request](https://github.com/peter-evans/create-pull-request)\n${{ env.SUPERSNYK_PR_BODY }}"
