name: SuperSnyk 次
description: "Detects automated Snyk PRs and adds 'snyk' label. Combines PRs with the 'snyk' label into a single SuperSnyk 次 PR. If a SuperSnyk 次 PR already exists, it will be updated."
inputs:
  github_token:
    description: "GitHub token i.e. secrets.GITHUB_TOKEN"
    required: true
    default: "CHANGE_ME"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: main # Should this be main? Hmm
        fetch-depth: 0

    - name: Add 'snyk' label to PR
      if: ${{ (startsWith(github.head_ref, 'snyk-fix-') || startsWith(github.head_ref, 'snyk-upgrade-')) && startsWith(github.event.pull_request.title, '[Snyk]') }}
      run: gh pr edit $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') --add-label 'snyk'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    # - uses: 8BitJonny/gh-get-current-pr@2.0.0
    #   id: PR
    #   with:
    #     github-token: ${{ inputs.github_token }}
    #     sha: ${{ github.event.pull_request.head.sha }}
    #     filterOutClosed: true
    #     filterOutDraft: 1

    # - run: echo "PR LABEL ${prLabel}"
    #   shell: bash
    #   if: success() && steps.PR.outputs.number
    #   env:
    #     prNumber: ${{ steps.PR.outputs.number }}
    #     prJSON: ${{ steps.PR.outputs.pr }}
    #     prLabel: ${{ steps.PR.outputs.pr_labels }}

    - uses: bobvanderlinden/combine-pull-requests@v3
      if: ${{ (startsWith(github.head_ref, 'snyk-fix-') || startsWith(github.head_ref, 'snyk-upgrade-')) && startsWith(github.event.pull_request.title, '[Snyk]') }}
      with:
        label: snyk
        repo-token: ${{ inputs.github_token }}

    - name: Get Snyk PRs metadata
      if: ${{ (startsWith(github.head_ref, 'snyk-fix-') || startsWith(github.head_ref, 'snyk-upgrade-')) && startsWith(github.event.pull_request.title, '[Snyk]') }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh
        $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Create SuperSnyk 次 PR
      if: ${{ (startsWith(github.head_ref, 'snyk-fix-') || startsWith(github.head_ref, 'snyk-upgrade-')) && startsWith(github.event.pull_request.title, '[Snyk]') }}
      uses: peter-evans/create-pull-request@v4
      with:
        title: 次 SuperSnyk
        body: "次 SuperSnyk PR created with [supersnyk](https://github.com/mishabruml/supersnyk)\n${{ env.SUPERSNYK_PR_BODY }}"
