name: SuperSnyk 次
description: "Combine multiple automated Snyk PRs into a single SuperSnyk 次 PR"
branding:
  icon: "git-pull-request"
  color: "orange"
inputs:
  github_token:
    description: "GitHub token i.e. secrets.GITHUB_TOKEN"
    required: true
    default: CHANGE_ME
  main_branch_name:
    description: The name of the main/base/default branch. Defaults to "main"
    default: main

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.main_branch_name }}

    - name: Detect if Snyk PR and set flag
      run: echo "IS_SNYK_PR=${{ (startsWith(github.head_ref, 'snyk-fix-') || startsWith(github.head_ref, 'snyk-upgrade-')) && startsWith(github.event.pull_request.title, '[Snyk]') }}" >> $GITHUB_ENV
      shell: bash

    - name: Add 'snyk' label to snyk PR
      if: env.IS_SNYK_PR
      run: gh pr edit $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') --add-label 'snyk'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    # - uses: bobvanderlinden/combine-pull-requests@v3
    #   if: env.IS_SNYK_PR
    #   with:
    #     label: snyk
    #     repo-token: ${{ inputs.github_token }}

    - name: Fetch Snyk PRs
      if: env.IS_SNYK_PR
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/get-snyk-prs.sh
        $GITHUB_ACTION_PATH/get-snyk-prs.sh

    - name: Create SuperSnyk 次 branch
      if: env.IS_SNYK_PR
      run: |
        git config pull.rebase false
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        git branch supersnyk ${{ inputs.main_branch_name }}
        git checkout supersnyk
        git pull origin ${{ env.SNYK_PR_BRANCH_NAMES }} --no-edit
        git push origin supersnyk

    # # Creates a PR with the new combined branch
    # - uses: actions/github-script@v3
        name: Create Combined Pull Request
        env:
          PRS_STRING: ${{ steps.fetch-branch-names.outputs.prs-string }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prString = process.env.PRS_STRING;
            const body = 'This PR was created by the Combine PRs action by combining the following PRs:\n' + prString;
            await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Combined PR',
              head: '${{ github.event.inputs.combineBranchName }}',
              base: '${{ steps.fetch-branch-names.outputs.base-branch }}',
              body: body
            });

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: supersnyk

    - name: Create SuperSnyk 次 PR
      if: env.IS_SNYK_PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: 次 SuperSnyk
        body: "次 SuperSnyk PR created with [supersnyk](https://github.com/mishabruml/supersnyk)\n${{ env.SUPERSNYK_PR_BODY }}"
