name: SuperSnyk 次
description: "Detects automated Snyk PRs and adds 'snyk' label. Combines PRs with the 'snyk' label into a single SuperSnyk 次 PR. If a SuperSnyk 次 PR already exists, it will be updated."
inputs:
  repo-token:
    description: "GitHub token i.e. secrets.GITHUB_TOKEN"
    required: true
    default: "CHANGE_ME"

runs:
  using: "composite"
  steps:
    - uses: TimonVS/pr-labeler-action@v3
      name: Detect and label Snyk PR for 次 SuperSnyk
      with:
        configuration-path: $GITHUB_ACTION_PATH/pr-labeler.yml
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
    # - run: gh pr view --json labels | jq '.labels | .[] | select(.name == "snykk")'
    #   shell: bash
    #   env:
    #     GITHUB_TOKEN: ${{ inputs.repo-token }}

    - uses: 8BitJonny/gh-get-current-pr@2.0.0
      with:
        github-token: ${{ inputs.repo-token }}
        # Verbose setting SHA when using Pull_Request event trigger to fix #16
        sha: ${{ github.event.pull_request.head.sha }}
        filterOutClosed: true
        filterOutDraft: 1
    - run: echo "Your PR is ${prNumber} and its JSON is ${prJSON}"
      if: success() && steps.PR.outputs.number
      env:
        prNumber: ${{ steps.PR.outputs.number }}
        # JSON object with the full PR object
        prJSON: ${{ steps.PR.outputs.pr }}
        # Direct access to common PR properties
        prUrl: ${{ steps.PR.outputs.pr_url }}
        prTitle: ${{ steps.PR.outputs.pr_title }}
        prBody: ${{ steps.PR.outputs.pr_body }}
        prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
        prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
        prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
        prLabel: ${{ steps.PR.outputs.pr_labels }}

    - uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - uses: bobvanderlinden/combine-pull-requests@v3
      with:
        label: snyk
        repo-token: ${{ inputs.repo-token }}
    - run: chmod +x $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh
      shell: bash
    - name: Get Snyk PRs metadata
      run: $GITHUB_ACTION_PATH/get-snyk-prs-metadata.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
    - name: Create SuperSnyk 次 PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: 次 SuperSnyk
        body: "次 SuperSnyk PR created with [create-pull-request](https://github.com/peter-evans/create-pull-request)\n${{ env.SUPERSNYK_PR_BODY }}"
