name: SuperSnyk 🦸
description: "Combine multiple automated Snyk PRs into a single SuperSnyk 🦸 PR"
branding:
  icon: "git-pull-request"
  color: "orange"
inputs:
  github_token:
    description: "GitHub token i.e. secrets.GITHUB_TOKEN"
    required: true
    default: CHANGE_ME
  main_branch_name:
    description: The name of the main/base/default branch. Defaults to "main"
    default: main

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.main_branch_name }}

    - name: Detect if Snyk PR and set flag
      run: echo "IS_SNYK_PR=${{ (startsWith(github.head_ref, 'snyk-fix-') || startsWith(github.head_ref, 'snyk-upgrade-')) && startsWith(github.event.pull_request.title, '[Snyk]') }}" >> $GITHUB_ENV
      shell: bash

    - name: Add 'snyk' label to snyk PR
      if: env.IS_SNYK_PR
      run: gh pr edit $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') --add-label 'snyk'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Get Snyk PRs
      if: env.IS_SNYK_PR
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/get-snyk-prs.sh
        $GITHUB_ACTION_PATH/get-snyk-prs.sh

    - name: Create SuperSnyk 🦸 commit
      if: env.IS_SNYK_PR
      shell: bash
      env:
        MAIN_BRANCH_NAME: ${{ inputs.main_branch_name }}
        SNYK_PR_BRANCH_NAMES: ${{ env.SNYK_PR_BRANCH_NAMES }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/create-supersnyk-commit.sh
        $GITHUB_ACTION_PATH/create-supersnyk-commit.sh

    - name: Create SuperSnyk 🦸 PR
      if: env.IS_SNYK_PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: 🦸 SuperSnyk
        body: "🦸 SuperSnyk PR created with [supersnyk](https://github.com/mishabruml/supersnyk)\n$(echo ${{ env.SUPERSNYK_PR_BODY }}) | sed -r 's/(closes #[0-9]+ )/&\n/g'"
        branch: supersnyk
        delete-branch: true
